version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "3001:3001"
    depends_on:
      - redis

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    depends_on:
      - redis

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      - redis