name: Docker Compose CI

on:
  push:
    branches: 
      - main
      - add-github-actions
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Docker Compose
      run: docker compose build
